image:
  - Ubuntu
  - Visual Studio 2017

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArhYh73Bz81BYPM1DvWai9rytUPvYKpvwN6jLyOG0znUr7oDcc0gy5lGCnHGge5mo2l5IDrHrrplwqWWys0Tz/eJraqaiXDFpPQFK18ulLKBPA1tkMIq2s+cOKdKkPYoVRMKzpTa9jDZYaAcT7olw0hBdAQ6FmypjnsNWVzpjsqE/0w9PYlJNB/Fsh3nhi/I8QDy9MM8v6ZyUsQtLHlsGfO6GjeRWLr9IS6S/8RdX73pYGxIAM/4m02tcNdvqt9FMu7ufF0OCmg915EM2EGIuBinLPGG/v57GPtkJ1a4gzOJtJFEiNMPLXJj8iGElSjd6cRiSsXx6yee9zs96QutRwQ==

install:
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

services:
  - docker # Ubuntu only

build: # Windows only
  project: .\desktop\Bililive_dm_VR\Bililive_dm_VR.sln
  verbosity: minimal

after_build:
  - ps: .\CI\after_build.ps1

for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - sh: docker run -v /home/appveyor/projects/bililive-dm-vr:/src --rm -i robinryf/unity3d:2018_1_0f2 run-unity.sh "-quit -batchmode -projectPath /src/renderer -executeMethod CIRunner.Build"
  artifacts:
    - path: build
  on_finish:
#   - sh: ./CI/block.sh

