image:
  - Ubuntu
  - Visual Studio 2017

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

matrix:
  fast_finish: true

for:
- matrix:
    only:
      - image: Ubuntu
  build_script:
    - sh: docker run -v /home/appveyor/projects/bililive-dm-vr:/src --rm -i robinryf/unity3d:2018_1_0f2 run-unity.sh "-quit -batchmode -projectPath /src/renderer -executeMethod CIRunner.Build"
  services:
    - docker
- matrix:
    only:
      - image: Visual Studio 2017
  build:
    project: .\desktop\Bililive_dm_VR\Bililive_dm_VR.sln
    verbosity: minimal
  after_build:
    - ps: .\CI\after_build.ps1

artifacts:
  - path: build
